const triviaQuestions = [
    { question: "What gas do plants breathe in that humans and animals breathe out?", answer: "Carbon dioxide" },
    { question: "How many legs does a spider have?", answer: "Eight" },
    { question: "What is the name of the toy cowboy in 'Toy Story'?", answer: "Woody" },
    { question: "What is the color of a school bus in the United States?", answer: "Yellow" },
    { question: "What fruit is known as the 'king of fruits' and is famous for its strong smell?", answer: "Durian" },
    { question: "What is the freezing point of water in degrees Celsius?", answer: "Zero" },
    { question: "What planet is known as the 'Red Planet'?", answer: "Mars" },
    { question: "Who lives in a pineapple under the sea?", answer: "SpongeBob SquarePants" },
    { question: "What type of animal is Disney's Dumbo?", answer: "Elephant" },
    { question: "What is the hardest substance in the human body?", answer: "Tooth enamel" },
    { question: "What do you use to write on a blackboard?", answer: "Chalk" },
    { question: "What does WWW stand for in a website browser?", answer: "World Wide Web" },
    { question: "Which season comes after summer?", answer: "Autumn" },
    { question: "What is the name of Mickey Mouse's dog?", answer: "Pluto" },
    { question: "What is the largest mammal in the world?", answer: "Blue Whale" },
    { question: "In which continent is the Sahara Desert located?", answer: "Africa" },
    { question: "How many colors are there in a rainbow?", answer: "Seven" },
    { question: "What is the main ingredient in guacamole?", answer: "Avocado" },
    { question: "What is the tallest mountain in the world?", answer: "Mount Everest" },
    { question: "What is the smallest country in the world?", answer: "Vatican City" },
    { question: "What is the capital city of Japan?", answer: "Tokyo" },
    { question: "How many teeth does an adult human have?", answer: "32" },
    { question: "What is the chemical symbol for gold?", answer: "Au" },
    { question: "What is the longest river in the world?", answer: "Nile" },
  ];
  
  module.exports = triviaQuestions;